import RPi.GPIO as GPIO

class MOTOR_DIRECTIONS:
    FORWARD_FRONT_LEFT=3
    FORWARD_FRONT_RIGHT=2
    FORWARD_REAR_LEFT=4
    FORWARD_REAR_RIGHT=17
    BACKWARD_FRONT_LEFT=14
    BACKWARD_FRONT_RIGHT=15
    BACKWARD_REAR_LEFT=18
    BACKWARD_REAR_RIGHT=23


def supplyPower( index ):
    GPIO.setmode(GPIO.BCM)
    GPIO.setup(index,GPIO.OUT)
    GPIO.output(index,True)
    
def cancelPower( index ):
    GPIO.setmode(GPIO.BCM)
    GPIO.setup(index,GPIO.OUT)
    GPIO.output(index,False)    

def forwardMotors():
    cancelPower( MOTOR_DIRECTIONS.BACKWARD_FRONT_LEFT )
    cancelPower( MOTOR_DIRECTIONS.BACKWARD_FRONT_RIGHT )
    cancelPower( MOTOR_DIRECTIONS.BACKWARD_REAR_LEFT)
    cancelPower( MOTOR_DIRECTIONS.BACKWARD_REAR_RIGHT ) 
    
    supplyPower( MOTOR_DIRECTIONS.FORWARD_FRONT_LEFT )
    supplyPower( MOTOR_DIRECTIONS.FORWARD_FRONT_RIGHT )
    supplyPower( MOTOR_DIRECTIONS.FORWARD_REAR_LEFT)
    supplyPower( MOTOR_DIRECTIONS.FORWARD_REAR_RIGHT )
    
def reverseMotors():
    cancelPower( MOTOR_DIRECTIONS.FORWARD_FRONT_LEFT )
    cancelPower( MOTOR_DIRECTIONS.FORWARD_FRONT_RIGHT )
    cancelPower( MOTOR_DIRECTIONS.FORWARD_REAR_LEFT )
    cancelPower( MOTOR_DIRECTIONS.FORWARD_REAR_RIGHT )
    
    supplyPower( MOTOR_DIRECTIONS.BACKWARD_FRONT_LEFT )
    supplyPower( MOTOR_DIRECTIONS.BACKWARD_FRONT_RIGHT )
    supplyPower( MOTOR_DIRECTIONS.BACKWARD_REAR_LEFT)
    supplyPower( MOTOR_DIRECTIONS.BACKWARD_REAR_RIGHT )
    
def moveRight():
    cancelPower( MOTOR_DIRECTIONS.FORWARD_FRONT_RIGHT )
    cancelPower( MOTOR_DIRECTIONS.FORWARD_REAR_RIGHT )
    cancelPower( MOTOR_DIRECTIONS.BACKWARD_REAR_LEFT)
    cancelPower( MOTOR_DIRECTIONS.BACKWARD_FRONT_LEFT )
    
    supplyPower( MOTOR_DIRECTIONS.BACKWARD_FRONT_RIGHT )
    supplyPower( MOTOR_DIRECTIONS.BACKWARD_REAR_RIGHT )
    
    supplyPower( MOTOR_DIRECTIONS.FORWARD_FRONT_LEFT )
    supplyPower( MOTOR_DIRECTIONS.FORWARD_REAR_LEFT)
    
    
def moveLeft():
    cancelPower( MOTOR_DIRECTIONS.FORWARD_FRONT_LEFT )
    cancelPower( MOTOR_DIRECTIONS.FORWARD_REAR_LEFT )
    cancelPower( MOTOR_DIRECTIONS.BACKWARD_FRONT_RIGHT )
    cancelPower( MOTOR_DIRECTIONS.BACKWARD_REAR_RIGHT )
    
    supplyPower( MOTOR_DIRECTIONS.BACKWARD_REAR_LEFT)
    supplyPower( MOTOR_DIRECTIONS.BACKWARD_FRONT_LEFT )
    
    supplyPower( MOTOR_DIRECTIONS.FORWARD_FRONT_RIGHT )
    supplyPower( MOTOR_DIRECTIONS.FORWARD_REAR_RIGHT)
    
    
def stopAll():
    cancelPower( MOTOR_DIRECTIONS.FORWARD_FRONT_LEFT )
    cancelPower( MOTOR_DIRECTIONS.FORWARD_FRONT_RIGHT )
    cancelPower( MOTOR_DIRECTIONS.FORWARD_REAR_LEFT )
    cancelPower( MOTOR_DIRECTIONS.FORWARD_REAR_RIGHT )
    cancelPower( MOTOR_DIRECTIONS.BACKWARD_FRONT_LEFT )
    cancelPower( MOTOR_DIRECTIONS.BACKWARD_FRONT_RIGHT )
    cancelPower( MOTOR_DIRECTIONS.BACKWARD_REAR_LEFT)
    cancelPower( MOTOR_DIRECTIONS.BACKWARD_REAR_RIGHT )   


    
